"""empty message

Revision ID: 34c86ab8b20a
Revises: ed264f4feab6
Create Date: 2019-08-03 14:02:32.956767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c86ab8b20a'
down_revision = 'ed264f4feab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('atp_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('turned_pro', sa.String(), nullable=True),
    sa.Column('weight_lbs', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('handedness', sa.String(length=1), nullable=True),
    sa.Column('backhand', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('r_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('r_name')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('t_name')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('best_of', sa.Integer(), nullable=True),
    sa.Column('m_date', sa.Date(), nullable=True),
    sa.Column('w_set1', sa.Integer(), nullable=True),
    sa.Column('l_set1', sa.Integer(), nullable=True),
    sa.Column('w_set2', sa.Integer(), nullable=True),
    sa.Column('l_set2', sa.Integer(), nullable=True),
    sa.Column('w_set3', sa.Integer(), nullable=True),
    sa.Column('l_set3', sa.Integer(), nullable=True),
    sa.Column('w_set4', sa.Integer(), nullable=True),
    sa.Column('l_set4', sa.Integer(), nullable=True),
    sa.Column('w_set5', sa.Integer(), nullable=True),
    sa.Column('l_set5', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('loser', sa.Integer(), nullable=False),
    sa.Column('t_round', sa.Integer(), nullable=True),
    sa.Column('tournament', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loser'], ['player.id'], ),
    sa.ForeignKeyConstraint(['t_round'], ['round.id'], ),
    sa.ForeignKeyConstraint(['tournament'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='temp_pkey')
    )
    op.drop_table('match')
    op.drop_table('tournament')
    op.drop_table('round')
    op.drop_table('player')
    # ### end Alembic commands ###
