"""empty message

Revision ID: cdf227488353
Revises: 34c86ab8b20a
Create Date: 2019-08-03 14:15:25.506312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf227488353'
down_revision = '34c86ab8b20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('loser_rank', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('winner_rank', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'match', ['id'])
    op.create_unique_constraint(None, 'player', ['id'])
    op.create_unique_constraint(None, 'round', ['id'])
    op.create_unique_constraint(None, 'tournament', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='unique')
    op.drop_constraint(None, 'round', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_column('match', 'winner_rank')
    op.drop_column('match', 'loser_rank')
    # ### end Alembic commands ###
